const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const data={
 quick:[['Visão Geral','visao'],['Escopo','escopo'],['Cronograma','cronograma'],['Mapa / 3D','mapa'],['Go / No-Go','prontidao'],['Equipe','equipe'],['Segurança','seguranca'],['Qualidade','qualidade'],['Documentos','documentos'],['Acompanhamento','acompanhamento']],
 scopes:{Estrutural:['Passadiço','Plataformas','Suportes','Adequações','Conexões','Alinhamento','Nivelamento','Prumo'],Mecânica:['Mesas','Roletes','Guias','Calha de transição','Proteções','Componentes do transportador'],Elétrica:['Desenergização','Bloqueio','Aterramento','Infraestrutura','Cabos','Conexões','Testes elétricos'],Correia:['Preparação','Lançamento da lona','Posicionamento','Emenda','Vulcanização','Tensionamento','Alinhamento'],Comissionamento:['Inspeções','Testes','Verificação de integridade','Liberação','Reenergização','Retorno operacional']},
 schedule:[['Preparação e mobilização','11/01','12/01','2 dias'],['Parada e bloqueio SE-2032KS-03','13/01','13/01','1 dia'],['Adequação estrutural','14/01','17/01','4 dias'],['Montagem mecânica','18/01','21/01','4 dias'],['Infraestrutura elétrica e cabos','18/01','23/01','6 dias'],['Lançamento da correia e vulcanização','24/01','27/01','4 dias'],['Testes e comissionamento','28/01','29/01','2 dias'],['Liberação para operação','30/01','30/01','1 dia']],
 readiness:[{name:'Projeto liberado',done:true,critical:true},{name:'Materiais disponíveis',done:true,critical:true},{name:'Equipe mobilizada',done:true,critical:true},{name:'ART e PTS',done:true,critical:true},{name:'Bloqueio planejado',done:true,critical:true},{name:'Equipamentos',done:false,critical:true},{name:'Equipe de vulcanização',done:false,critical:true},{name:'Inspeções definidas',done:true,critical:false}],
 timeline:['Preparação','Parada Programada','Bloqueio / LOTO','Verificação de Energia Zero','Aterramento Temporário','Adequações Estruturais','Interligação Estrutural','Montagem Mecânica','Infraestrutura Elétrica','Lançamento de Cabos','Lançamento da Correia','Vulcanização','Inspeções','Testes','Comissionamento','Retirada dos Bloqueios','Reenergização','Liberação Operacional'],
 progress:{Estrutural:50,Mecânica:30,Elétrica:20,Correia:0,Comissionamento:0},
 team:['Engenharia / Supervisão','Encarregado','Técnico de Segurança','Inspetor de Solda / Dimensional','Eletricistas Força e Controle','Eletricista Montador','Montadores Mecânicos','Operador de Munck','Operador de Guindaste','Motorista / Veículo de Apoio'],
 equipment:['Guindaste','Caminhão Munck','Geradores','Andaimes','Detector de tensão','Aterramento temporário','Equipamentos de sinalização','Ferramentas elétricas','Equipamentos de trabalho em altura'],
 risks:['Risco elétrico','Trabalho em altura','Içamento','Interferências','Equipamentos móveis','Atividade simultânea'],
 quality:['Inspeção dimensional','Verificação de alinhamento','Nivelamento / Prumo','Inspeção de soldagem','Torqueamento de conexões','Inspeção da emenda / vulcanização','Registros de inspeção','Checklists','Critérios de liberação'],
 docs:[['Manual do Tie-in','PDF','assets/docs/manual-tiein.pdf',true],['Plano de Trabalho','PDF','assets/docs/plano-trabalho.pdf',true],['Cronograma Integrado','PDF','assets/docs/cronograma.pdf',true],['Desenhos de Referência','DWG/PDF','',false],['Procedimento de Vulcanização','PDF','',false],['ART','PDF','',false],['PTS','PDF','',false],['Checklists','PDF/XLSX','',false],['RAC’s / Normas','PDF','',false],['Relatórios','PDF','',false]],
 evidence:[['antes','assets/img/foto-local-01.jpg','Registro inicial do local'],['durante','assets/img/foto-local-02.jpg','Evidência de execução']]
};
function render(){
 $('#quick').innerHTML=data.quick.map(x=>`<a href="#${x[1]}">${x[0]}</a>`).join('');
 $('#scopeGrid').innerHTML=Object.entries(data.scopes).map(([k,v],i)=>`<article class="scope-card card"><span class="num">0${i+1}</span><h3>${k}</h3><ul>${v.map(x=>`<li>${x}</li>`).join('')}</ul></article>`).join('');
 $('#scheduleBody').innerHTML=data.schedule.map((x,i)=>`<tr><td>0${i+1}</td><td><b>${x[0]}</b></td><td>${x[1]}</td><td>${x[2]}</td><td>${x[3]}</td><td><span class="badge">Planejado</span></td></tr>`).join('');
 const pct=Math.round(data.readiness.filter(x=>x.done).length/data.readiness.length*100),go=data.readiness.filter(x=>x.critical).every(x=>x.done); $('#readyPct').textContent=pct+'%'; $('#gauge').style.setProperty('--pct',pct+'%'); $('#goStatus').textContent=go?'GO':'NO-GO'; $('#goStatus').style.color=go?'var(--success)':'var(--danger)'; $('#readinessList').innerHTML=data.readiness.map(x=>`<div class="check-item"><span>${x.name}${x.critical?' <small>· crítico</small>':''}</span><b class="${x.done?'ok':'warn'}">${x.done?'✓ APROVADO':'! PENDENTE'}</b></div>`).join('');
 $('#timeline').innerHTML=data.timeline.map((x,i)=>`<div class="step"><i></i><b>${String(i+1).padStart(2,'0')}</b><span>${x}</span></div>`).join('');
 $('#progressBars').innerHTML=Object.entries(data.progress).map(([k,v])=>`<div class="bar"><div class="bar-head"><b>${k}</b><span>${v}%</span></div><div class="track"><div class="fill" style="width:${v}%"></div></div></div>`).join(''); $('#overallDonut').style.setProperty('--pct','35%');
 $('#team').innerHTML=data.team.map(x=>`<div class="list-item">${x}</div>`).join(''); $('#equipment').innerHTML=data.equipment.map(x=>`<div class="list-item">${x}</div>`).join('');
 $('#risks').innerHTML=data.risks.map(x=>`<article class="risk-card card"><h3>${x}</h3><p>Controle a detalhar conforme análise de risco e documentação oficial.</p></article>`).join('');
 $('#quality').innerHTML=data.quality.map((x,i)=>`<article class="quality-card card"><h3>${x}</h3><p>Registro e critério conforme documentação aplicável.</p><span class="qstatus">${i%3===0?'Em inspeção':i%3===1?'Pendente':'Liberado'}</span></article>`).join('');
 $('#docs').innerHTML=data.docs.map(x=>`<div class="doc-row"><div class="doc-icon">▤</div><b>${x[0]}</b><span>${x[1]}</span><span>${x[3]?'Previsto':'Pendente'}</span><button data-doc="${x[2]}">Abrir</button></div>`).join('');
 $('#evidence').innerHTML=data.evidence.map(x=>`<article class="evidence-card project-image" data-kind="${x[0]}" data-src="${x[1]}"><div class="placeholder"><b>IMAGEM DO PROJETO</b><small>${x[1]}</small></div><div class="evidence-meta"><small>${x[0].toUpperCase()}</small><b>${x[2]}</b></div></article>`).join(''); hydrateImages();
}
function hydrateImages(){ $$('.project-image').forEach(el=>{const src=el.dataset.src;if(!src)return;const im=new Image();im.onload=()=>{el.style.backgroundImage=`url('${src}')`; const ph=$('.placeholder',el);if(ph)ph.style.display='none'};im.src=src}) }
render();
$('#hamb').onclick=()=>$('#nav').classList.toggle('open'); $$('#nav a').forEach(a=>a.onclick=()=>$('#nav').classList.remove('open'));
$$('.map-toolbar button').forEach(b=>b.onclick=()=>{$$('.map-toolbar button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const v=$('#mapView');v.dataset.src=b.dataset.map;v.style.backgroundImage='';$('.placeholder',v).style.display='flex';$('.placeholder small',v).textContent=b.dataset.map;hydrateImages()});
const modal=$('#modal'); function openModal(html){$('#modalContent').innerHTML=html;modal.classList.add('open');modal.setAttribute('aria-hidden','false')} $('#modalClose').onclick=()=>modal.classList.remove('open'); modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};
$('#expand').onclick=()=>{const src=$('#mapView').dataset.src;openModal(`<img src="${src}" alt="Imagem ampliada" onerror="this.outerHTML='<div style=\'padding:80px;text-align:center\'><b>IMAGEM DO PROJETO</b><br><small>${src}</small></div>'">`)};
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
$('#docs').onclick=e=>{if(e.target.tagName!=='BUTTON')return;const p=e.target.dataset.doc;if(p)window.open(p,'_blank');else toast('Documento ainda não disponibilizado.')}; $('#register').onclick=()=>openModal('<div style="padding:35px 10px;text-align:center"><h3>Registrar</h3><p>Funcionalidade prevista para versão futura.</p></div>');
$$('.filters button').forEach(b=>b.onclick=()=>{$$('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.evidence-card').forEach(c=>c.style.display=b.dataset.filter==='all'||c.dataset.kind===b.dataset.filter?'block':'none')});
window.addEventListener('scroll',()=>$('#topBtn').classList.toggle('show',scrollY>500));$('#topBtn').onclick=()=>scrollTo({top:0,behavior:'smooth'});$('#searchBtn').onclick=()=>toast('Busca preparada para evolução futura.');
